name: food_app
description: A basic UI scaffold for the Food App.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^7.1.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
